# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ef1d4f1d0f10d84cbac40c9ee52b61a05ab3c1f35a1ab3092aba6dcb6e043aac03c26d4685a1d61b1659ba3eb1c50d33e55b4837ef1253636be07064f5ad5e2

test:
  secret_key_base: 31ab122ee46ba0d46165be2f90c65bdb642f30d605266c3a0f1ca0c0090679066d6ac3214c575c9e16340c7f664da784950ffd77122497a1ca62de7f6e62108f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
